### ISSUE TITLE
Tokey.rs is still down

### ISSUE THREAD

**Issue by vncoelho** [XAMPPRocky/tokei_rs#15]
https://tokei.rs looks to be down.

**Comment by XAMPPRocky** [comment]
@vncoelho You may need to clear your cache as it is back up for me and I see it available on "Is it down right now". https://www.isitdownrightnow.com/tokei.rs.html

**Comment by XAMPPRocky** [comment]
I'm sorry you're having that issue. If I can verify that server is working from an external source, there's nothing more I can do about your problem. I'd recommend flushing your DNS cache, and if that doesn't work maybe contact Cloudflare support. 

No one is paying me to maintain these projects or their surrounding infrastructure. So until the complaints from around the globe materialise into money to actually support me providing this service, I have no obligation to provide any more stable a service than I choose to.

**Comment by Bruflot** [comment]
@XAMPPRocky 

It seems the issue is limited to accessing the site through https. This is just speculation, but I believe `isitdownrightnow.com` accesses the site through http, thus reports that it's loading fine. 
Here are the results of trying to load a badge through https (from uptrends.com):

![](https://i.imgur.com/fts945X.png)

The reported errors are all 521.

**Comment by XAMPPRocky** [comment]
@Bruflot Thank you for that, I've now resolved that issue.
