### ISSUE TITLE
Userscript for injecting LoC in GitHub repo page

### ISSUE THREAD

**Issue by miraclx** [XAMPPRocky/tokei_rs#89]
I just put together a script that, using `tokei_rs`, injects the lines of code into the summary view of the GitHub repository page.

https://gist.github.com/miraclx/aad03f43fe8ac85682b0243f4f242f0d

Is this useful to add to the readme?

![Demo](https://user-images.githubusercontent.com/16881812/107178227-00108d00-69d4-11eb-8fed-0cf910af070b.png)

It does, however, require the use of a user script manager like [Violentmonkey](https://violentmonkey.github.io/).

EDIT: click to view badge, added helpful tooltip

> ![Tooltip Demo](https://user-images.githubusercontent.com/16881812/107192294-be8cdb80-69ed-11eb-839c-6accb2485349.png)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This looks cool, however I'm not sure about including it in the README, since due to the nature of user scripts it's not guaranteed to always work, if they make changes. It's also something I wouldn't be maintaining so I would feel a bit weird about promoting a script I have no control over. Feel free to share it with other people though!

**Comment by miraclx** [comment]
Thank you for your reply! I totally understand, it feels a little out of place here. Just figured I'd open an issue for reference in case others might find it interesting.

And thanks for tokei by the way, have a great day!
